# Generated by Django 5.2.3 on 2025-08-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='consultation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='rating_avg',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
