# Generated by Django 5.1.3 on 2025-08-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='iban_number',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
