# Generated by Django 5.2.5 on 2025-08-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expertprofile_consultation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
