# Generated by Django 5.1.3 on 2025-08-25 08:33

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertprofile',
            options={'verbose_name': 'Expert Profile', 'verbose_name_plural': 'Expert Profiles'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='consultation_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('career_path', 'اختيار المسار المهني'), ('study_path', 'اختيار المسار الدراسي'), ('university_choices', 'مراجعة خيارات التخصصات الجامعية'), ('general_inquiry', 'استفسار عام')], max_length=57, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='specialties',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('academic_guidance', 'إرشاد أكاديمي'), ('career_guidance', 'توجيه مهني'), ('self_development', 'تطوير الذات'), ('cv_writing', 'كتابة السيرة الذاتية')], max_length=61, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='hourly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='stage',
            field=models.CharField(blank=True, choices=[('middle', 'متوسط'), ('high', 'ثانوي'), ('university', 'جامعي')], max_length=50, null=True),
        ),
    ]
