# Generated by Django 5.1.3 on 2025-08-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
