# Generated by Django 5.2.3 on 2025-08-28 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='ai_interview_attempts',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='consultations_attempts',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='ai_interview_remaining',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='consultations_remaining',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='plan',
            name='attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ConsumptionLog',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
