# Generated by Django 5.2.5 on 2025-08-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_path', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathsession',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'جارية'), ('FINISHED', 'منتهية')], default='RUNNING', max_length=20),
        ),
    ]
