# Generated by Django 5.2.5 on 2025-08-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_path', '0002_alter_pathsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathsession',
            name='major',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pathsession',
            name='mode',
            field=models.CharField(choices=[('SCHOOL', 'طلاب المدارس/المقبلون على الجامعة'), ('GRAD', 'الخريجون/المقبلون على الوظيفة')], default='SCHOOL', max_length=10),
        ),
    ]
