# Generated by Django 5.2.3 on 2025-08-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='price_at_booking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
