# Generated by Django 5.2.5 on 2025-08-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0002_interviewsession_guest_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='weaknesses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
